//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vechile_Tracking_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomer
    {
        public long CustomerID { get; set; }
        public string CustomerRefNo { get; set; }
        public string CustomerTitle { get; set; }
        public long CompanyID { get; set; }
        public long ParentCustomerID { get; set; }
        public long CustomerCategoryID { get; set; }
        public long CustomerTypeID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public long BranchID { get; set; }
        public long NationalID { get; set; }
        public long RegionID { get; set; }
        public long AreaID { get; set; }
        public long TerritoryID { get; set; }
        public long TownID { get; set; }
        public long RouteID { get; set; }
        public string TelNo { get; set; }
        public string FaxNo { get; set; }
        public string Email { get; set; }
        public string OwnerName { get; set; }
        public long ModeOfPaymentID { get; set; }
        public string GSTNo { get; set; }
        public string NTNNo { get; set; }
        public bool IsBlock { get; set; }
        public bool IsDoubleTripAllowed { get; set; }
        public bool IsLooseProductCustomer { get; set; }
        public bool IsPONumberRequired { get; set; }
        public bool IsResigned { get; set; }
        public bool IsMonOff { get; set; }
        public bool IsTueOff { get; set; }
        public bool IsWedOff { get; set; }
        public bool IsThuOff { get; set; }
        public bool IsFriOff { get; set; }
        public bool IsSatOff { get; set; }
        public bool IsSunOff { get; set; }
        public string OpenTime { get; set; }
        public string CloseTime { get; set; }
        public bool IsMonDispatch { get; set; }
        public bool IsTueDispatch { get; set; }
        public bool IsWedDispatch { get; set; }
        public bool IsThuDispatch { get; set; }
        public bool IsFriDispatch { get; set; }
        public bool IsSatDispatch { get; set; }
        public bool IsSunDispatch { get; set; }
        public bool IsActive { get; set; }
        public bool IsAdminUpdated { get; set; }
        public bool IsSubDistributer { get; set; }
        public int CreditDays { get; set; }
        public double CreditLimit { get; set; }
        public bool IsPaymentInfoReqOnDO { get; set; }
        public long BusinessUnitID { get; set; }
        public string ElinkCustomerRefNo { get; set; }
    }
}
