//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vechile_Tracking_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSupplier
    {
        public long SupplierID { get; set; }
        public string SupplierRefNo { get; set; }
        public string SupplierTitle { get; set; }
        public string OldCode { get; set; }
        public long CompanyID { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string TelNo { get; set; }
        public string FaxNo { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public bool IsActive { get; set; }
    }
}
