//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vechile_Tracking_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblTransporter
    {
        public long TransporterID { get; set; }
        public string TransporterRefNo { get; set; }
        public string OldCode { get; set; }
        public string TransporterTitle { get; set; }
        public string TransporterType { get; set; }
        public int TotalVehicles { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string TelNo { get; set; }
        public string FaxNo { get; set; }
        public string Email { get; set; }
        public string WebSite { get; set; }
        public int PreferenceNo { get; set; }
        public long CompanyID { get; set; }
        public int IsActive { get; set; }
    }
}
