//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vechile_Tracking_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int Log_Id { get; set; }
        public Nullable<int> User_Id { get; set; }
        public string User_name { get; set; }
        public Nullable<System.DateTime> Login_Time { get; set; }
        public Nullable<System.DateTime> Logout_Time { get; set; }
        public string Host_Name { get; set; }
    }
}
