//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vechile_Tracking_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityLog
    {
        public int DocId { get; set; }
        public Nullable<System.DateTime> DateTime { get; set; }
        public string QRCodeNo { get; set; }
        public string ActivityType { get; set; }
    }
}
