//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vechile_Tracking_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChildForm
    {
        public int ID { get; set; }
        public string ChildFormName { get; set; }
        public Nullable<int> ParentId { get; set; }
    }
}
