//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vechile_Tracking_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_List
    {
        public int ClientID { get; set; }
        public int ProjectID { get; set; }
        public int SubProjectID { get; set; }
        public int ParentID { get; set; }
        public int FormID { get; set; }
        public string Description { get; set; }
        public string Header { get; set; }
        public string Category { get; set; }
        public string Path { get; set; }
        public string ShortName { get; set; }
    }
}
