//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vechile_Tracking_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Form_Value
    {
        public int ClientID { get; set; }
        public int ProjectID { get; set; }
        public int SubProjectID { get; set; }
        public int ParentID { get; set; }
        public int FormID { get; set; }
        public int ComponentID { get; set; }
        public int HierarchyNo { get; set; }
        public Nullable<int> SelectionID { get; set; }
        public string Parameter_Desc { get; set; }
        public string Label { get; set; }
        public string Stored_Procedure { get; set; }
    }
}
