//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vechile_Tracking_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GRReport
    {
        public int ReportId { get; set; }
        public string WareHouse { get; set; }
        public string ItemCode { get; set; }
        public string GRIRNo { get; set; }
        public string TransferNoteNo { get; set; }
        public string TypeOfTransfer { get; set; }
        public string Rejection { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
