//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vechile_Tracking_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public int Report_Id { get; set; }
        public string Report_Description { get; set; }
        public Nullable<int> Parent_Id { get; set; }
        public string Report_Path { get; set; }
    }
}
