//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vechile_Tracking_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class table_MainGate
    {
        public string TranID { get; set; }
        public string TransactionID { get; set; }
        public string PONumber { get; set; }
        public string DocNo { get; set; }
        public string Dispatch_Others { get; set; }
        public string VehicleEntryFor { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Depot { get; set; }
        public Nullable<System.DateTime> DocDate { get; set; }
        public string PartyType { get; set; }
        public Nullable<System.DateTime> PODate { get; set; }
        public string PartyDescription { get; set; }
        public string Product { get; set; }
        public string PhysicalQuantity { get; set; }
        public string UOM { get; set; }
        public string ShipmentDcoumentNo { get; set; }
        public string ShipmentDocumentDate { get; set; }
        public string ShipmentRemarks1 { get; set; }
        public string ShipmentRemarks2 { get; set; }
    }
}
