//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vechile_Tracking_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Driver
    {
        public long DriverID { get; set; }
        public string DriverRefNo { get; set; }
        public string DriverTitle { get; set; }
        public long TransporterID { get; set; }
        public string NIC { get; set; }
        public string TelNo { get; set; }
        public string MobileNo { get; set; }
        public long CompanyID { get; set; }
        public int IsActive { get; set; }
    }
}
