//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vechile_Tracking_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductType
    {
        public long ProductTypeID { get; set; }
        public string ProductTypeRefNo { get; set; }
        public string ProductTypeTitle { get; set; }
        public double Weight { get; set; }
        public long CompanyID { get; set; }
        public bool IsActive { get; set; }
    }
}
