//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vechile_Tracking_Systems.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblVehicleEntryDetailProduct
    {
        public long TranDtlID { get; set; }
        public long TranID { get; set; }
        public long CompanyID { get; set; }
        public long ProductID { get; set; }
        public string Description { get; set; }
        public double Quantity { get; set; }
        public long UOMID { get; set; }
    }
}
